# <center>AIM 5001 Module 6 Assignment (100 Points)<center>
Our Module 6 Assignment makes use of the functionality provided by Python’s NumPy package.

## 1. (10 Points) Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b, your output should contain only one 2 even if array a contains more than one 2 within it.

In [4]:
import numpy as np

__First of all, find the overlapping values. By using unique() function will only show distinct values.__

In [5]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(np.unique(a[np.isin(a,b)]))

[2 4]


## 2. (10 Points) Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you do not need to explicitly key in every integer value.

|col1|col2|col3|
|:--:|:--:|:--:|
|1|6|11|
|2|7|12|
|3|8|13|
|4|9|14|
|5|10|15|

__Using the arange function to generate 1-15 in a 1D array. By using the reshape function and transposing the matrix, we can have the above result.__

In [6]:
arr=np.arange(1,16,1)
arr=arr.reshape(3,5).T
print(arr)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


## 3. (10 Points) The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

__First of all, transpose the 2-D array to make the right sequence after flattening.
There are three ways to flatten the 2-D array:__

__1. flatten function__

__2. reshape(-1)__

__3. reshape(15,)__

In [7]:
arrT=arr.T # arr is the result of problem2
flatten_arr_1=arrT.flatten()
flatten_arr_2=arrT.reshape(-1)
flatten_arr_3=arrT.reshape(15,)
print(flatten_arr_1)
print(flatten_arr_2)
print(flatten_arr_3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## 4. (15 Points) Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.

__Since we want the columns to be different dimensions, we transpose the result of problem 2 first. Then use the reshape() function to transform.__

In [13]:
threeD_arr=arr.T.reshape(3,5,1) # arr is the result of problem 2
print(threeD_arr)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]


## 5. (15 Points) Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.

__First of all, transfer the shape into a 2-D array. In order to keep 1-5, 6-10, and 11-15 as columns, we use (3,5) to reshape the 3-D array. Then, use the T function to transpose the 2-D array.__ 

In [16]:
backarray=threeD_arr.reshape(3,5).T #threeD_arr is the result of problem 4
print(backarray)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


## 6. (10 Points) You are given the following two arrays:

a = np.array([12, 5, 7, 15, 3, 1, 8])

b = np.array([14, 6, 3, 11, 19, 12, 5])

Write a Python/Numpy code block that removes from array a any items that are also present in array b.

__np.isin(a,b) will find characters in array a that are also in array b. Using the '\~' to inverse the condition, that is to find characters not in array b. [~np.isin(a,b)] will return boolean values that meet the condition.__

In [65]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
print(a[~np.isin(a,b)])

[ 7 15  1  8]


## 7. (30 Points) For this problem you will load a small data set to your online GitHub repository and then read it into a NumPy 2D array. You will then use the content that NumPy array to answer a series of analytical questions.

__Loading csv file from Github and storing the data as a 2-D array__

In [18]:
import pandas
import numpy as np

In [19]:
np.set_printoptions(suppress = True)
nyc_water = pandas.read_csv(r'https://raw.githubusercontent.com/shenghanyueh/AIM-5001/main/Module6_Data.csv').to_numpy()
type(nyc_water)

numpy.ndarray

__Show the 2-D array__

In [20]:
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

##  Q1:What is the maximum yearly NYC consumption of water in millions of gallons per day?

__Slicing the array to extract the column of water consumption (column 2, if column 0 is the first column). Using max() function to find the answer.__

In [21]:
print('Ans:',nyc_water[:,2].max(axis=0),'millions of gallons per day')

Ans: 1512.0 millions of gallons per day


## Q2:How many calendar years are represented within this data set? NumPy's shape command is one way to find out.

__The number of rows is the number of years that have been recorded. So we extract shape[0].__

In [22]:
print('Ans:',nyc_water.shape[0],'years')

Ans: 39 years


## Q3:What is the mean and the standard deviation of the per capita daily water consumption?

__Slicing the array to extract the column of capita daily water consumption (column 3, if column 0 is the first column). Using mean() and std() functions to find the answer of mean and standard deviation.__

In [80]:
print('mean:',nyc_water[:,3].mean())
print('standard deviation:',nyc_water[:,3].std())

mean: 160.30769230769232
standard deviation: 31.51894330370624


## Q4:What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

__Slicing the array to extract the number of population (column 1, if column 0 is the first column). Using diff function will generate the number of differences in population between years.__

In [23]:
pop_diff=np.diff(nyc_water[:,1])
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
